[package]
name = "wsr"
version = "0.1.0"
authors = ["weathfold <weathfold@li-dev.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.12.0"
image = "0.23.14"
wgpu = "0.8.1"